In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

from sqlalchemy import create_engine
import pymysql

%matplotlib inline

## Art Recommender

### 1. Load Data

In [2]:
sqlEngine       = create_engine('mysql+pymysql://root:sabrina_art@127.0.0.1:3301/sabrina_art')
dbConnection    = sqlEngine.connect()

In [3]:
allArtworks = pd.read_sql("select id as artwork_id from artworks LIMIT 100", dbConnection)

In [4]:
allArtworks.head()

                 artwork_id
0  4d8b92eb4eb68a1b2c000968
1  4d8b92ee4eb68a1b2c0009ab
2  4d8b93394eb68a1b2c0010fa
3  4d8b937c4eb68a1b2c001722
4  4d8b93b04eb68a1b2c001b9d

In [5]:
allArtworks.shape

(100, 1)

In [6]:
allArtworks.dtypes

artwork_id    object
dtype: object

In [7]:
for index, row in allArtworks.iterrows():
    
    artwork_id = row["artwork_id"]    
    genes_table = pd.read_sql("SELECT * FROM artworks_to_genes WHERE artwork_id LIKE '"+ artwork_id +"'", dbConnection)
    
    for index2, gene in genes_table.iterrows():
        
        gene_id = gene["gene_id"]
        allArtworks.loc[index, gene_id] = 1
        
        
allArtworks = allArtworks.fillna(0)
allArtworks.head(100)

,artwork_id,56539404ebad647f5493ac0f,51b662438b3b81ec2700027d,505b5a9b930ad000020008e0,517eed481386d1fb350001e5,4d90d18fdcdd5f44a500002e,515b44b6d0c2ebb9420007c4,5182bea34b72c8f22300005d,56c337486428707983000236,4dcdf34f8080ad0001003a83,...,4ebc3cc74f1217000100424b,5238cb9aa09a67af5c00028c,4d90d193dcdd5f44a5000089,4e6035e1e890b100012525ef,4e60333fe890b10001248c87,52601d0acd530e7fa400014f,506485437c58620002000441,4dcdfa875797fc0001003f78,554a6854726169061ae10600,50d103c66f0775b45b000819
0,4d8b92eb4eb68a1b2c000968,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4d8b92ee4eb68a1b2c0009ab,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4d8b93394eb68a1b2c0010fa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4d8b937c4eb68a1b2c001722,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4d8b93b04eb68a1b2c001b9d,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4eb40a1199ddd70001001c30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
96,4eb40adf53257b000100226e,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
97,4eb40bf5a71fcf0001002643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
98,4eb40dbc248a2600010043fe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
99,4eb412d54a75ce00010005b2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0